version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
    stdin_open: true
    # tty: true
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  bundle:
